### ISSUE TITLE
UI: link tabs on code blocks

### ISSUE THREAD

**Issue by riverKanies** [bitcoindevkit/book-of-bdk#48]
so that a user doesn't have to select their preffered language for every code block individually
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#linked-tabs

also, hey y'all, hope you don't mind me submitting this. I was looking through the book and just noticed this would be a nice UI improvement

**Comment by riverKanies** [comment]
submitted a pr for this. ended up being pretty hacky and I'm not totally sure this is the direction to go with it...

**Comment by riverKanies** [comment]
turns out there was a built in solution https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
not sure how I got to those other docs 😅

**Comment by thunderbiscuit** [comment]
Sweet! Well it's good to know about those third-party maintained plugins anyway so I'm glad you found them!
