### ISSUE TITLE
Update Page: Starter Example, add context

### ISSUE THREAD

**Issue by riverKanies** [bitcoindevkit/book-of-bdk#57]
I think it'd be nice to add a little context to this example. I may go ahead and work up a PR for this to see what y'all think.

Here are some note's I've been taking on this:

from book, page /cookbook/starter/

`let client: esplora_client::BlockingClient = Builder::new("http://signet.bitcoindevkit.net").build_blocking();
`
looks like the docs default to using an esplora client hosted by the bdk team. they also default to using signet. the reasoning for these choices should be mentioned somewhere.

why signet?
signet is basically just a better version of testnet. it gives more control to the node operaters so that they can do controlled experiements like on regtest but with more realistic network conditions like testnet. it actually allows the ability to make network conditions more similar to mainnet than testnet.

why esplora?
esplora offers the most functionality and convienience for bdk use and wallet development, so bdk hosts a signet esplora “client”. using this network option will give the wallet developer a relatively realistic blockchain without the security considerations of interacting with the live bitcoin network (mainnet).

could also throw in a link to explain the diff between blockchain clients https://chatgpt.com/share/66fec1d1-32e8-8005-a257-211ad07f7c73

**Comment by riverKanies** [comment]
I also think it would be good to link to a resource on a breakdown of the differences between network options. as a developer I would assume regtest would be best, like for automated tests, but the bitcoin ecosystem is different than normal software development, and there are a lot of benefits to signet. this could also be just a link to a chatGPT answer in my opinion. I think having even an AI generated page that was read over by the bdk team and considered a helpful resource is better than just leaving the reader to try looking for resources or expect them to use chatgpt themselves (even tho that is a pretty safe assumption these days).

Again, I'm assuming the reader here is "I've read mastering bitcoin" level familiar with bitcoin, and could be totally new to wallet development (and therefore hasn't considered blockchain clients or test networks)

**Comment by riverKanies** [comment]
thinking about this further I think it might be best to simply add two links to this example:
- breakdown of blockchain clients
- breakdown of networks

I think it'd be great to have a page for each of these topics. and then this example could give a very short sentence or two on why we're using these defaults and where to learn more

**Comment by notmandatory** [comment]
I like the idea of making an assumption that readers of the book of bdk have read some other foundational books like ["mastering bitcoin"](https://github.com/bitcoinbook/bitcoinbook) and ["programming bitcoin"](https://github.com/jimmysong/programmingbitcoin). We should put links to those near the beginning and avoid tangents into bitcoin topics that are are already covered well other places. Other high quality references are to the original [BIPs](https://github.com/bitcoin/bips/blob/master/README.mediawiki) or to the [Bitcoin Optech topics](https://bitcoinops.org/en/topics/) page. I think we can avoid having our own glossary if we link to these sources liberally.

For example mastering bitcoin ch. 11 explains different networks. However I don't know of any good references that explain the differences between blockchain clients like esplora, electrum, CBF.

**Comment by riverKanies** [comment]
@notmandatory I agree, I think linking to mastering bitcoin (and programming bitcoin) and explicitly saying that they are "required reading" on like probably the first page of the docs is a great idea.
I also agree that linking to ch11 is likely a good idea for the networks comparison page, in that case I'd still want just a sentence or paragraph on why we're using signet, and then a link to ch11.
Perhaps having a more thorough breakdown of blockchain clients in the docs would be appropriate on the other hand if there isn't a great, concise resource handy for that.

**Comment by riverKanies** [comment]
another topic that I think is worth giving some context on is descriptor creation and usage. In the starter example there is a private key based descriptor being used, and there is a link to a page that shows how to create your own private key and similar descriptor. I think it would be worth being more explicit about whether the reader should generate their own, and perhaps mention if there is a faucet where they can get some tBTC to play with. 
It looks like for the starter example itself, it would actually make sense to use the example descriptor to see a non-zero balance immediately, but if readers are actually going to be doing transactions we can't have them all using the same master key (for various reasons). perhaps for the starter example we could not include a private key, if all we want to do is show a balance... 
perhaps the answer to some of these questions will become more clear as we get more examples. like if we're going to be walking through sending a transaction we probably want descriptor creation, faucet, a bdk owned address to send to (faucet I guess) and way to inspect the transaction made it into a block etc...

**Comment by riverKanies** [comment]
ended up putting just highlights from these 3 pages in a few sentences in the example
