### ISSUE TITLE
Use "snippets" from code that compiles

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/book-of-bdk#61]
It will be easier to ensure that our code snippets always work if we use the ["Snippet Lines"](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-lines) feature. What I have in mind is we maintain rust/kotlin/swift/etc. projects in the `companion-code` part of the repo then CI can verify it (formatted, lints, compiles). Then in the book itself we reference the lines in the companion-code projects. We should also have comments in the companion-code that let us know which parts of the book each snippet is linked to.

**Comment by riverKanies** [comment]
I think it would actually be better to use snippet sections https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-sections that way we don't have to update line numbers every time an example has a line added

**Comment by notmandatory** [comment]
Oh ya I didn't see this feature, I agree named snippet sections is a better way to go.

**Comment by riverKanies** [comment]
@notmandatory this issue can be closed now that the PR was merged
