### ISSUE TITLE
Add page: Migrating from 0.X

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/book-of-bdk#81]

**Comment by ValuedMammal** [comment]
I'm looking into this. It looks like the way to do it is to have page in the cookbook along with a new rust example crate. I plan to use the code from bitcoindevkit/bdk#1648. The markdown file could possibly be added to the `persistence` folder or perhaps make a new directory for this and future examples of how to update to the next major version. Are there any other ideas to consider?

**Comment by thunderbiscuit** [comment]
Depending on the size of the page, I'd add it as a custom 1-off page to the sidebar as part of the `Getting Started` navbar section, or maybe add a fully new sidebar group in the `Cookbook` called `Migrating from older versions`?

Feel free to add it just to persistence if that's easier and we can figure out where to fit it best once it's in.
